[[plugins-inputs-heartbeat]]
=== heartbeat



Generate heartbeat messages.

The general intention of this is to test the performance and
availability of Logstash.


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
heartbeat {
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-heartbeat-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-heartbeat-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-heartbeat-count>> |<<number,number>>|No|`-1`
| <<plugins-inputs-heartbeat-interval>> |<<number,number>>|No|`60`
| <<plugins-inputs-heartbeat-message>> |<<string,string>>|No|`"ok"`
| <<plugins-inputs-heartbeat-tags>> |<<array,array>>|No|
| <<plugins-inputs-heartbeat-threads>> |<<number,number>>|No|`1`
| <<plugins-inputs-heartbeat-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-heartbeat-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-heartbeat-charset]]
===== `charset`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  <li> Value type is <<string,string>>
  * There is no default value for this setting.

The character encoding used in this input. Examples include `UTF-8`
and `cp1252`

This setting is useful if your log files are in `Latin-1` (aka `cp1252`)
or in another character set other than `UTF-8`.

This only affects `plain` format logs since json is `UTF-8` already.

[[plugins-inputs-heartbeat-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-heartbeat-count]]
===== `count` 

  * Value type is <<number,number>>
  * Default value is `-1`

How many times to iterate.
This is typically used only for testing purposes.

[[plugins-inputs-heartbeat-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`



[[plugins-inputs-heartbeat-format]]
===== `format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `plain`, `json`, `json_event`, `msgpack_event`
  * There is no default value for this setting.

The format of input data (plain, json, json_event)

[[plugins-inputs-heartbeat-interval]]
===== `interval` 

  * Value type is <<number,number>>
  * Default value is `60`

Set how frequently messages should be sent.

The default, `60`, means send a message every 60 seconds.

[[plugins-inputs-heartbeat-message]]
===== `message` 

  * Value type is <<string,string>>
  * Default value is `"ok"`

The message string to use in the event.

If you set this to `epoch` then this plugin will use the current
timestamp in unix timestamp (which is by definition, UTC).  It will
output this value into a field called `clock`

If you set this to `sequence` then this plugin will send a sequence of
numbers beginning at 0 and incrementing each interval.  It will
output this value into a field called `clock`

Otherwise, this value will be used verbatim as the event message. It
will output this value into a field called `message`

[[plugins-inputs-heartbeat-message_format]]
===== `message_format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

If format is `json`, an event `sprintf` string to build what
the display `@message` should be given (defaults to the raw JSON).
`sprintf` format strings look like `%{fieldname}`

If format is `json_event`, ALL fields except for `@type`
are expected to be present. Not receiving all fields
will cause unexpected results.

[[plugins-inputs-heartbeat-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-heartbeat-threads]]
===== `threads` 

  * Value type is <<number,number>>
  * Default value is `1`



[[plugins-inputs-heartbeat-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


