[[plugins-inputs-lumberjack]]
=== lumberjack



Receive events using the lumberjack protocol.

This is mainly to receive events shipped with lumberjack[http://github.com/jordansissel/lumberjack],
now represented primarily via the
https://github.com/elasticsearch/logstash-forwarder[Logstash-forwarder].


&nbsp;

==== Synopsis

This plugin supports the following configuration options:


Required configuration options:

[source,json]
--------------------------
lumberjack {
    port => ...
    ssl_certificate => ...
    ssl_key => ...
}
--------------------------



Available configuration options:

[cols="<,<,<,<m",options="header",]
|=======================================================================
|Setting |Input type|Required|Default value
| <<plugins-inputs-lumberjack-add_field>> |<<hash,hash>>|No|`{}`
| <<plugins-inputs-lumberjack-codec>> |<<codec,codec>>|No|`"plain"`
| <<plugins-inputs-lumberjack-host>> |<<string,string>>|No|`"0.0.0.0"`
| <<plugins-inputs-lumberjack-port>> |<<number,number>>|Yes|
| <<plugins-inputs-lumberjack-ssl_certificate>> |a valid filesystem path|Yes|
| <<plugins-inputs-lumberjack-ssl_key>> |a valid filesystem path|Yes|
| <<plugins-inputs-lumberjack-ssl_key_passphrase>> |<<password,password>>|No|
| <<plugins-inputs-lumberjack-tags>> |<<array,array>>|No|
| <<plugins-inputs-lumberjack-type>> |<<string,string>>|No|
|=======================================================================



==== Details

&nbsp;

[[plugins-inputs-lumberjack-add_field]]
===== `add_field` 

  * Value type is <<hash,hash>>
  * Default value is `{}`

Add a field to an event

[[plugins-inputs-lumberjack-charset]]
===== `charset`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  <li> Value type is <<string,string>>
  * There is no default value for this setting.

The character encoding used in this input. Examples include `UTF-8`
and `cp1252`

This setting is useful if your log files are in `Latin-1` (aka `cp1252`)
or in another character set other than `UTF-8`.

This only affects `plain` format logs since json is `UTF-8` already.

[[plugins-inputs-lumberjack-codec]]
===== `codec` 

  * Value type is <<codec,codec>>
  * Default value is `"plain"`

The codec used for input data. Input codecs are a convenient method for decoding your data before it enters the input, without needing a separate filter in your Logstash pipeline.

[[plugins-inputs-lumberjack-debug]]
===== `debug`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<boolean,boolean>>
  * Default value is `false`



[[plugins-inputs-lumberjack-format]]
===== `format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value can be any of: `plain`, `json`, `json_event`, `msgpack_event`
  * There is no default value for this setting.

The format of input data (plain, json, json_event)

[[plugins-inputs-lumberjack-host]]
===== `host` 

  * Value type is <<string,string>>
  * Default value is `"0.0.0.0"`

The IP address to listen on.

[[plugins-inputs-lumberjack-max_clients]]
===== `max_clients`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<number,number>>
  * Default value is `1000`

Number of maximum clients that the lumberjack input will accept, this allow you
to control the back pressure up to the client and stop logstash to go OOM with 
connection. This settings is a temporary solution and will be deprecated really soon.

[[plugins-inputs-lumberjack-message_format]]
===== `message_format`  (DEPRECATED)

  * DEPRECATED WARNING: This configuration item is deprecated and may not be available in future versions.
  * Value type is <<string,string>>
  * There is no default value for this setting.

If format is `json`, an event `sprintf` string to build what
the display `@message` should be given (defaults to the raw JSON).
`sprintf` format strings look like `%{fieldname}`

If format is `json_event`, ALL fields except for `@type`
are expected to be present. Not receiving all fields
will cause unexpected results.

[[plugins-inputs-lumberjack-port]]
===== `port` 

  * This is a required setting.
  * Value type is <<number,number>>
  * There is no default value for this setting.

The port to listen on.

[[plugins-inputs-lumberjack-ssl_certificate]]
===== `ssl_certificate` 

  * This is a required setting.
  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL certificate to use.

[[plugins-inputs-lumberjack-ssl_key]]
===== `ssl_key` 

  * This is a required setting.
  * Value type is <<path,path>>
  * There is no default value for this setting.

SSL key to use.

[[plugins-inputs-lumberjack-ssl_key_passphrase]]
===== `ssl_key_passphrase` 

  * Value type is <<password,password>>
  * There is no default value for this setting.

SSL key passphrase to use.

[[plugins-inputs-lumberjack-tags]]
===== `tags` 

  * Value type is <<array,array>>
  * There is no default value for this setting.

Add any number of arbitrary tags to your event.

This can help with processing later.

[[plugins-inputs-lumberjack-type]]
===== `type` 

  * Value type is <<string,string>>
  * There is no default value for this setting.

Add a `type` field to all events handled by this input.

Types are used mainly for filter activation.

The type is stored as part of the event itself, so you can
also use the type to search for it in Kibana.

If you try to set a type on an event that already has one (for
example when you send an event from a shipper to an indexer) then
a new input will not override the existing type. A type set at
the shipper stays with that event for its life even
when sent to another Logstash server.


